FROM zabbix/zabbix-web-service:alpine-7.2.6

# Install Chromium and required fonts
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ttf-freefont \
    && mkdir -p /var/cache/chromium

# Set Chromium binary path as Zabbix expects it
ENV CHROMIUM_BIN="/usr/bin/chromium-browser"

# Optional: Confirm versions
RUN chromium-browser --version

# Entrypoint already defined in base image
